# Generated by Django 2.2.4 on 2019-08-14 10:57

from django.db import migrations


def is_new_building(construction_year, min_construction_year_for_new_building=2015):
    return construction_year >= min_construction_year_for_new_building


def fill_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    all_flats = Flat.objects.all()

    for flat in all_flats:
        flat.new_building = is_new_building(flat.construction_year)

    Flat.objects.bulk_update(all_flats, ['new_building'])


def clear_new_building_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    Flat.objects.all().update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field, clear_new_building_field),
    ]
