# Generated by Django 2.2.4 on 2019-08-15 17:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_flat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owners_phone_pure',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='нормализованный номер владельца'),
        ),
    ]
