# Generated by Django 2.2.4 on 2019-08-15 17:16

from django.db import migrations
import phonenumbers


def fill_owners_phone_pure_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    all_flats = Flat.objects.all()

    for flat in all_flats:
        phone_number_object = phonenumbers.parse(flat.owners_phonenumber, 'RU')

        if phonenumbers.is_valid_number(phone_number_object):
            flat.owners_phone_pure = phonenumbers.format_number(
                numobj=phone_number_object,
                num_format=phonenumbers.PhoneNumberFormat.E164,
            )

    Flat.objects.bulk_update(all_flats, ['owners_phone_pure'])


def clear_owners_phone_pure_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    Flat.objects.all().update(owners_phone_pure='')


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_owners_phone_pure'),
    ]

    operations = [
        migrations.RunPython(fill_owners_phone_pure_field, clear_owners_phone_pure_field),
    ]
