# Generated by Django 2.2.4 on 2019-08-16 17:00

from django.db import migrations


def fill_owners_table(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        owner, _ = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_number=flat.owners_phonenumber,
            normalized_phone_number=flat.owners_phone_pure,
        )
        owner.flats.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(fill_owners_table),
    ]
