# Generated by Django 2.2.4 on 2019-08-16 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20190816_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'жалоба', 'verbose_name_plural': 'жалобы'},
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'квартира', 'verbose_name_plural': 'квартиры'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'владелец', 'verbose_name_plural': 'владельцы'},
        ),
    ]
