# Generated by Django 2.2.4 on 2019-08-16 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20190816_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, verbose_name='активно ли объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='адрес квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.IntegerField(db_index=True, null=True, verbose_name='год постройки здания'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='когда создано объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.TextField(blank=True, verbose_name='текст объявления'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.CharField(help_text='Первый этаж, последний этаж, пятый этаж', max_length=3, verbose_name='этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.NullBooleanField(db_index=True, verbose_name='наличие балкона'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.IntegerField(db_index=True, verbose_name='цена квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms_number',
            field=models.IntegerField(db_index=True, verbose_name='количество комнат в квартире'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town',
            field=models.CharField(db_index=True, max_length=50, verbose_name='город, где находится квартира'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town_district',
            field=models.CharField(blank=True, help_text='Чертаново Южное', max_length=50, verbose_name='район города, где находится квартира'),
        ),
    ]
