# Generated by Django 2.2.4 on 2019-08-17 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0012_auto_20190816_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='likes',
        ),
        migrations.AddField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='кто лайкнул'),
        ),
    ]
